services:
  - type: web
    name: ai-exe
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildFilter:
      paths:
        - Dockerfile
        - requirements.txt
        - AI.py
